// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package illuminate

// Get Helper method for Bot.GetBusinessConnection.
func (bc BusinessConnection) Get(b *Bot, opts *GetBusinessConnectionOpts) (*BusinessConnection, error) {
	return b.GetBusinessConnection(bc.ID, opts)
}

// Answer Helper method for Bot.AnswerCallbackQuery.
func (cq CallbackQuery) Answer(b *Bot, opts *AnswerCallbackQueryOpts) (bool, error) {
	return b.AnswerCallbackQuery(cq.ID, opts)
}

// ApproveJoinRequest Helper method for Bot.ApproveChatJoinRequest.
func (c Chat) ApproveJoinRequest(b *Bot, userID int64, opts *ApproveChatJoinRequestOpts) (bool, error) {
	return b.ApproveChatJoinRequest(c.ID, userID, opts)
}

// BanMember Helper method for Bot.BanChatMember.
func (c Chat) BanMember(b *Bot, userID int64, opts *BanChatMemberOpts) (bool, error) {
	return b.BanChatMember(c.ID, userID, opts)
}

// BanSenderChat Helper method for Bot.BanChatSenderChat.
func (c Chat) BanSenderChat(b *Bot, senderChatID int64, opts *BanChatSenderChatOpts) (bool, error) {
	return b.BanChatSenderChat(c.ID, senderChatID, opts)
}

// CreateInviteLink Helper method for Bot.CreateChatInviteLink.
func (c Chat) CreateInviteLink(b *Bot, opts *CreateChatInviteLinkOpts) (*ChatInviteLink, error) {
	return b.CreateChatInviteLink(c.ID, opts)
}

// DeclineJoinRequest Helper method for Bot.DeclineChatJoinRequest.
func (c Chat) DeclineJoinRequest(b *Bot, userID int64, opts *DeclineChatJoinRequestOpts) (bool, error) {
	return b.DeclineChatJoinRequest(c.ID, userID, opts)
}

// DeletePhoto Helper method for Bot.DeleteChatPhoto.
func (c Chat) DeletePhoto(b *Bot, opts *DeleteChatPhotoOpts) (bool, error) {
	return b.DeleteChatPhoto(c.ID, opts)
}

// DeleteStickerSet Helper method for Bot.DeleteChatStickerSet.
func (c Chat) DeleteStickerSet(b *Bot, opts *DeleteChatStickerSetOpts) (bool, error) {
	return b.DeleteChatStickerSet(c.ID, opts)
}

// EditInviteLink Helper method for Bot.EditChatInviteLink.
func (c Chat) EditInviteLink(b *Bot, inviteLink string, opts *EditChatInviteLinkOpts) (*ChatInviteLink, error) {
	return b.EditChatInviteLink(c.ID, inviteLink, opts)
}

// ExportInviteLink Helper method for Bot.ExportChatInviteLink.
func (c Chat) ExportInviteLink(b *Bot, opts *ExportChatInviteLinkOpts) (string, error) {
	return b.ExportChatInviteLink(c.ID, opts)
}

// Get Helper method for Bot.GetChat.
func (c Chat) Get(b *Bot, opts *GetChatOpts) (*Chat, error) {
	return b.GetChat(c.ID, opts)
}

// GetAdministrators Helper method for Bot.GetChatAdministrators.
func (c Chat) GetAdministrators(b *Bot, opts *GetChatAdministratorsOpts) ([]ChatMember, error) {
	return b.GetChatAdministrators(c.ID, opts)
}

// GetMember Helper method for Bot.GetChatMember.
func (c Chat) GetMember(b *Bot, userID int64, opts *GetChatMemberOpts) (ChatMember, error) {
	return b.GetChatMember(c.ID, userID, opts)
}

// GetMemberCount Helper method for Bot.GetChatMemberCount.
func (c Chat) GetMemberCount(b *Bot, opts *GetChatMemberCountOpts) (int64, error) {
	return b.GetChatMemberCount(c.ID, opts)
}

// GetMenuButton Helper method for Bot.GetChatMenuButton.
func (c Chat) GetMenuButton(b *Bot, opts *GetChatMenuButtonOpts) (MenuButton, error) {
	if opts == nil {
		opts = &GetChatMenuButtonOpts{}
	}

	if opts.ChatID == nil {
		opts.ChatID = &c.ID
	}

	return b.GetChatMenuButton(opts)
}

// GetUserBoosts Helper method for Bot.GetUserChatBoosts.
func (c Chat) GetUserBoosts(b *Bot, userID int64, opts *GetUserChatBoostsOpts) (*UserChatBoosts, error) {
	return b.GetUserChatBoosts(c.ID, userID, opts)
}

// Leave Helper method for Bot.LeaveChat.
func (c Chat) Leave(b *Bot, opts *LeaveChatOpts) (bool, error) {
	return b.LeaveChat(c.ID, opts)
}

// PinMessage Helper method for Bot.PinChatMessage.
func (c Chat) PinMessage(b *Bot, messageID int64, opts *PinChatMessageOpts) (bool, error) {
	return b.PinChatMessage(c.ID, messageID, opts)
}

// PromoteMember Helper method for Bot.PromoteChatMember.
func (c Chat) PromoteMember(b *Bot, userID int64, opts *PromoteChatMemberOpts) (bool, error) {
	return b.PromoteChatMember(c.ID, userID, opts)
}

// RestrictMember Helper method for Bot.RestrictChatMember.
func (c Chat) RestrictMember(b *Bot, userID int64, permissions ChatPermissions, opts *RestrictChatMemberOpts) (bool, error) {
	return b.RestrictChatMember(c.ID, userID, permissions, opts)
}

// RevokeInviteLink Helper method for Bot.RevokeChatInviteLink.
func (c Chat) RevokeInviteLink(b *Bot, inviteLink string, opts *RevokeChatInviteLinkOpts) (*ChatInviteLink, error) {
	return b.RevokeChatInviteLink(c.ID, inviteLink, opts)
}

// SendAction Helper method for Bot.SendChatAction.
func (c Chat) SendAction(b *Bot, action string, opts *SendChatActionOpts) (bool, error) {
	return b.SendChatAction(c.ID, action, opts)
}

// SetAdministratorCustomTitle Helper method for Bot.SetChatAdministratorCustomTitle.
func (c Chat) SetAdministratorCustomTitle(b *Bot, userID int64, customTitle string, opts *SetChatAdministratorCustomTitleOpts) (bool, error) {
	return b.SetChatAdministratorCustomTitle(c.ID, userID, customTitle, opts)
}

// SetDescription Helper method for Bot.SetChatDescription.
func (c Chat) SetDescription(b *Bot, opts *SetChatDescriptionOpts) (bool, error) {
	return b.SetChatDescription(c.ID, opts)
}

// SetMenuButton Helper method for Bot.SetChatMenuButton.
func (c Chat) SetMenuButton(b *Bot, opts *SetChatMenuButtonOpts) (bool, error) {
	if opts == nil {
		opts = &SetChatMenuButtonOpts{}
	}

	if opts.ChatID == nil {
		opts.ChatID = &c.ID
	}

	return b.SetChatMenuButton(opts)
}

// SetPermissions Helper method for Bot.SetChatPermissions.
func (c Chat) SetPermissions(b *Bot, permissions ChatPermissions, opts *SetChatPermissionsOpts) (bool, error) {
	return b.SetChatPermissions(c.ID, permissions, opts)
}

// SetPhoto Helper method for Bot.SetChatPhoto.
func (c Chat) SetPhoto(b *Bot, photo InputFile, opts *SetChatPhotoOpts) (bool, error) {
	return b.SetChatPhoto(c.ID, photo, opts)
}

// SetStickerSet Helper method for Bot.SetChatStickerSet.
func (c Chat) SetStickerSet(b *Bot, stickerSetName string, opts *SetChatStickerSetOpts) (bool, error) {
	return b.SetChatStickerSet(c.ID, stickerSetName, opts)
}

// SetTitle Helper method for Bot.SetChatTitle.
func (c Chat) SetTitle(b *Bot, title string, opts *SetChatTitleOpts) (bool, error) {
	return b.SetChatTitle(c.ID, title, opts)
}

// UnbanMember Helper method for Bot.UnbanChatMember.
func (c Chat) UnbanMember(b *Bot, userID int64, opts *UnbanChatMemberOpts) (bool, error) {
	return b.UnbanChatMember(c.ID, userID, opts)
}

// UnbanSenderChat Helper method for Bot.UnbanChatSenderChat.
func (c Chat) UnbanSenderChat(b *Bot, senderChatID int64, opts *UnbanChatSenderChatOpts) (bool, error) {
	return b.UnbanChatSenderChat(c.ID, senderChatID, opts)
}

// UnpinAllMessages Helper method for Bot.UnpinAllChatMessages.
func (c Chat) UnpinAllMessages(b *Bot, opts *UnpinAllChatMessagesOpts) (bool, error) {
	return b.UnpinAllChatMessages(c.ID, opts)
}

// UnpinMessage Helper method for Bot.UnpinChatMessage.
func (c Chat) UnpinMessage(b *Bot, opts *UnpinChatMessageOpts) (bool, error) {
	return b.UnpinChatMessage(c.ID, opts)
}

// Copy Helper method for Bot.CopyMessage.
func (im InaccessibleMessage) Copy(b *Bot, chatID int64, opts *CopyMessageOpts) (*MessageID, error) {
	return b.CopyMessage(chatID, im.Chat.ID, im.MessageID, opts)
}

// Delete Helper method for Bot.DeleteMessage.
func (im InaccessibleMessage) Delete(b *Bot, opts *DeleteMessageOpts) (bool, error) {
	return b.DeleteMessage(im.Chat.ID, im.MessageID, opts)
}

// EditCaption Helper method for Bot.EditMessageCaption.
func (im InaccessibleMessage) EditCaption(b *Bot, opts *EditMessageCaptionOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageCaptionOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = im.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = im.MessageID
	}

	return b.EditMessageCaption(opts)
}

// EditLiveLocation Helper method for Bot.EditMessageLiveLocation.
func (im InaccessibleMessage) EditLiveLocation(b *Bot, latitude float64, longitude float64, opts *EditMessageLiveLocationOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageLiveLocationOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = im.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = im.MessageID
	}

	return b.EditMessageLiveLocation(latitude, longitude, opts)
}

// EditMedia Helper method for Bot.EditMessageMedia.
func (im InaccessibleMessage) EditMedia(b *Bot, media InputMedia, opts *EditMessageMediaOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageMediaOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = im.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = im.MessageID
	}

	return b.EditMessageMedia(media, opts)
}

// EditReplyMarkup Helper method for Bot.EditMessageReplyMarkup.
func (im InaccessibleMessage) EditReplyMarkup(b *Bot, opts *EditMessageReplyMarkupOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageReplyMarkupOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = im.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = im.MessageID
	}

	return b.EditMessageReplyMarkup(opts)
}

// EditText Helper method for Bot.EditMessageText.
func (im InaccessibleMessage) EditText(b *Bot, text string, opts *EditMessageTextOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageTextOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = im.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = im.MessageID
	}

	return b.EditMessageText(text, opts)
}

// Forward Helper method for Bot.ForwardMessage.
func (im InaccessibleMessage) Forward(b *Bot, chatID int64, opts *ForwardMessageOpts) (*Message, error) {
	return b.ForwardMessage(chatID, im.Chat.ID, im.MessageID, opts)
}

// Pin Helper method for Bot.PinChatMessage.
func (im InaccessibleMessage) Pin(b *Bot, opts *PinChatMessageOpts) (bool, error) {
	return b.PinChatMessage(im.Chat.ID, im.MessageID, opts)
}

// SetReaction Helper method for Bot.SetMessageReaction.
func (im InaccessibleMessage) SetReaction(b *Bot, opts *SetMessageReactionOpts) (bool, error) {
	return b.SetMessageReaction(im.Chat.ID, im.MessageID, opts)
}

// StopLiveLocation Helper method for Bot.StopMessageLiveLocation.
func (im InaccessibleMessage) StopLiveLocation(b *Bot, opts *StopMessageLiveLocationOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &StopMessageLiveLocationOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = im.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = im.MessageID
	}

	return b.StopMessageLiveLocation(opts)
}

// Unpin Helper method for Bot.UnpinChatMessage.
func (im InaccessibleMessage) Unpin(b *Bot, opts *UnpinChatMessageOpts) (bool, error) {
	if opts == nil {
		opts = &UnpinChatMessageOpts{}
	}

	if opts.MessageID == nil {
		opts.MessageID = &im.MessageID
	}

	return b.UnpinChatMessage(im.Chat.ID, opts)
}

// Answer Helper method for Bot.AnswerInlineQuery.
func (iq InlineQuery) Answer(b *Bot, results []InlineQueryResult, opts *AnswerInlineQueryOpts) (bool, error) {
	return b.AnswerInlineQuery(iq.ID, results, opts)
}

// Copy Helper method for Bot.CopyMessage.
func (m Message) Copy(b *Bot, chatID int64, opts *CopyMessageOpts) (*MessageID, error) {
	return b.CopyMessage(chatID, m.Chat.ID, m.MessageID, opts)
}

// Delete Helper method for Bot.DeleteMessage.
func (m Message) Delete(b *Bot, opts *DeleteMessageOpts) (bool, error) {
	return b.DeleteMessage(m.Chat.ID, m.MessageID, opts)
}

// EditCaption Helper method for Bot.EditMessageCaption.
func (m Message) EditCaption(b *Bot, opts *EditMessageCaptionOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageCaptionOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = m.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = m.MessageID
	}

	return b.EditMessageCaption(opts)
}

// EditLiveLocation Helper method for Bot.EditMessageLiveLocation.
func (m Message) EditLiveLocation(b *Bot, latitude float64, longitude float64, opts *EditMessageLiveLocationOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageLiveLocationOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = m.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = m.MessageID
	}

	return b.EditMessageLiveLocation(latitude, longitude, opts)
}

// EditMedia Helper method for Bot.EditMessageMedia.
func (m Message) EditMedia(b *Bot, media InputMedia, opts *EditMessageMediaOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageMediaOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = m.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = m.MessageID
	}

	return b.EditMessageMedia(media, opts)
}

// EditReplyMarkup Helper method for Bot.EditMessageReplyMarkup.
func (m Message) EditReplyMarkup(b *Bot, opts *EditMessageReplyMarkupOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageReplyMarkupOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = m.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = m.MessageID
	}

	return b.EditMessageReplyMarkup(opts)
}

// EditText Helper method for Bot.EditMessageText.
func (m Message) EditText(b *Bot, text string, opts *EditMessageTextOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &EditMessageTextOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = m.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = m.MessageID
	}

	return b.EditMessageText(text, opts)
}

// Forward Helper method for Bot.ForwardMessage.
func (m Message) Forward(b *Bot, chatID int64, opts *ForwardMessageOpts) (*Message, error) {
	return b.ForwardMessage(chatID, m.Chat.ID, m.MessageID, opts)
}

// Pin Helper method for Bot.PinChatMessage.
func (m Message) Pin(b *Bot, opts *PinChatMessageOpts) (bool, error) {
	return b.PinChatMessage(m.Chat.ID, m.MessageID, opts)
}

// SetReaction Helper method for Bot.SetMessageReaction.
func (m Message) SetReaction(b *Bot, opts *SetMessageReactionOpts) (bool, error) {
	return b.SetMessageReaction(m.Chat.ID, m.MessageID, opts)
}

// StopLiveLocation Helper method for Bot.StopMessageLiveLocation.
func (m Message) StopLiveLocation(b *Bot, opts *StopMessageLiveLocationOpts) (*Message, bool, error) {
	if opts == nil {
		opts = &StopMessageLiveLocationOpts{}
	}

	if opts.ChatID == 0 {
		opts.ChatID = m.Chat.ID
	}
	if opts.MessageID == 0 {
		opts.MessageID = m.MessageID
	}

	return b.StopMessageLiveLocation(opts)
}

// Unpin Helper method for Bot.UnpinChatMessage.
func (m Message) Unpin(b *Bot, opts *UnpinChatMessageOpts) (bool, error) {
	if opts == nil {
		opts = &UnpinChatMessageOpts{}
	}

	if opts.MessageID == nil {
		opts.MessageID = &m.MessageID
	}

	return b.UnpinChatMessage(m.Chat.ID, opts)
}

// Answer Helper method for Bot.AnswerPreCheckoutQuery.
func (pcq PreCheckoutQuery) Answer(b *Bot, ok bool, opts *AnswerPreCheckoutQueryOpts) (bool, error) {
	return b.AnswerPreCheckoutQuery(pcq.ID, ok, opts)
}

// Answer Helper method for Bot.AnswerShippingQuery.
func (sq ShippingQuery) Answer(b *Bot, ok bool, opts *AnswerShippingQueryOpts) (bool, error) {
	return b.AnswerShippingQuery(sq.ID, ok, opts)
}

// GetChatBoosts Helper method for Bot.GetUserChatBoosts.
func (u User) GetChatBoosts(b *Bot, chatID int64, opts *GetUserChatBoostsOpts) (*UserChatBoosts, error) {
	return b.GetUserChatBoosts(chatID, u.ID, opts)
}

// GetProfilePhotos Helper method for Bot.GetUserProfilePhotos.
func (u User) GetProfilePhotos(b *Bot, opts *GetUserProfilePhotosOpts) (*UserProfilePhotos, error) {
	return b.GetUserProfilePhotos(u.ID, opts)
}
